// ===================================================================== //
// == This file is generated by the Contentful.ModelsGenerator.Cli    == //
// ===================================================================== //
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contentful.Core.Models;

namespace Contentful.Implementation.Models;

#pragma warning disable CS8669
internal partial record Blog
{
    public const string ContentTypeId = "blog";
    public required SystemProperties Sys { get; set; }
    public required string Title { get; set; }
    public required string Slug { get; set; }
    public required string Author { get; set; }
    public DateTime CreationDate { get; set; }
    public required string Content { get; set; }
}
#pragma warning restore CS8669

