// ===================================================================== //
// == This file is generated by the Contentful.ModelsGenerator.Cli    == //
// ===================================================================== //
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contentful.Core.Models;

namespace Contentful.Implementation.Models;

#pragma warning disable CS8669
internal partial record ContentPage
{
    public const string ContentTypeId = "contentPage";
    public required SystemProperties Sys { get; set; }
    public required string Title { get; set; }
    public required string Slug { get; set; }
    public required string Summary { get; set; }
    public Asset? Image { get; set; }
    public string? Author { get; set; }
    public Document? Content { get; set; }
}
#pragma warning restore CS8669

