// ===================================================================== //
// == This file is generated by the Contentful.ModelsGenerator.Cli    == //
// ===================================================================== //
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contentful.Core.Models;

namespace Contentful.Implementation.Models;

#pragma warning disable CS8669
internal partial record ExternalLink
{
    public const string ContentTypeId = "externalLink";
    public required SystemProperties Sys { get; set; }
    public required string Url { get; set; }
    public required string Text { get; set; }
    public string? HelpText { get; set; }
}
#pragma warning restore CS8669

