// ===================================================================== //
// == This file is generated by the Contentful.ModelsGenerator.Cli    == //
// ===================================================================== //
using System;
using System.Collections.Generic;
using Contentful.Core.Configuration;

namespace Contentful.Implementation.Models;

#pragma warning disable CS8669

internal partial class GeneratedContentTypeResolver : IContentTypeResolver
{
    private readonly Dictionary<string, Type> types = new Dictionary<string, Type>()
    {
        [ContentPage.ContentTypeId] = typeof(ContentPage),
    };

    public Type? Resolve(string contentTypeId)
    {
        return types.TryGetValue(contentTypeId, out var type) ? type : null;
    }
}
#pragma warning restore CS8669

