// ===================================================================== //
// == This file is generated by the Contentful.ModelsGenerator.Cli    == //
// ===================================================================== //
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contentful.Core.Models;

namespace Contentful.Implementation.Models;

#pragma warning disable CS8669
internal partial record Note
{
    public const string ContentTypeId = "note";
    public required SystemProperties Sys { get; set; }
    public required string Title { get; set; }
    public DateTime Date { get; set; }
    public string? Content { get; set; }
}
#pragma warning restore CS8669

