######################################################################
#     This workflow will build the Shared.ModelsGenerator.Cli of     #
#                         Peereflits                                 #
######################################################################
name: 'Build, test and publish Shared.ModelsGenerator.Cli'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  API_KEY : ${{ secrets.PAT_CLASSIC }}
  DOTNET_SOLUTION: src/ModelsGenerator.Cli.sln
  TESTSETTINGS_APIKEY: ${{ secrets.TESTSETTINGS_APIKEY }}
  TESTSETTINGS_SPACEID: ${{ secrets.TESTSETTINGS_SPACEID }}
  TESTSETTINGS_ENVIRONMENT: master

jobs:
  build-and-test:
    name: Build & test & publish
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT : Test

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Restore and build
      run: |
        dotnet restore ${{ env.DOTNET_SOLUTION }}
        dotnet build ${{ env.DOTNET_SOLUTION }} --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ${{ env.DOTNET_SOLUTION }} --configuration Release --no-restore --no-build --verbosity normal -e TestSettings:ApiKey="${{ env.TESTSETTINGS_APIKEY }}" -e TestSettings:SpaceId="${{ env.TESTSETTINGS_SPACEID }}" -e TestSettings:Environment="${{ env.TESTSETTINGS_ENVIRONMENT }}"

    - name: Pack & Push
      run: |
        dotnet pack ${{ env.DOTNET_SOLUTION }} --configuration Release --no-build --no-restore
        dotnet nuget add source --username peereflits --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/peereflits/index.json"
        dotnet nuget push **/*.nupkg --api-key ${{ env.API_KEY }} --skip-duplicate --source github
